package raisa.config;

public enum VisualizerConfigItemEnum {

	ALL_CONFIG_ITEMS, 
	INPUT_OUTPUT_TARGET, 
	LOCALIZATION_MODE,
	DISPLAY_ROBOT, DISPLAY_MAP, DISPLAY_TRAIL, DISPLAY_SIMULATOR, DISPLAY_PARTICLES, DISPLAY_IR_SCAN, DISPLAY_SONAR_SCAN,
	DISPLAYED_MEASUREMENTS, 
	DISPLAYED_CONTROLS,
	ACTIVATED_ALGORITHMS;

}
