package raisa.config;

public enum VisualizerConfigItemEnum {

	INPUT_OUTPUT_TARGET, LOCALIZATION_MODE, ALL_CONFIG_ITEMS, 
	DISPLAY_ROBOT, DISPLAY_MAP, DISPLAY_TRAIL, DISPLAY_SIMULATOR, DISPLAY_PARTICLES, DISPLAY_IR_SCAN, DISPLAY_SONAR_SCAN,
	DISPLAYED_MEASUREMENTS;

}
