package raisa.config;

public enum VisualizerConfigItemEnum {

	ALL_CONFIG_ITEMS, 
	INPUT_OUTPUT_TARGET, 
	LOCALIZATION_MODE,
	DISPLAYED_MAP_AREA_ELEMENTS,
	DISPLAYED_MEASUREMENTS, 
	DISPLAYED_CONTROLS,
	ACTIVATED_ALGORITHMS;

}
